controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    odrive_forward_controller:
      type: forward_command_controller/ForwardCommandController

odrive_forward_controller:
  ros__parameters:
    joints:
      - arm
    interface_name: position
